name: Run AddressSanitizer

on:
  push:

jobs:
  run-asan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        with:
          ref: fca53c77996ab0b723dd4ee5235671cba9274ca7

      - name: Install dependencies for project (Linux)
        if: runner.os == 'Linux'
        run: | 
          sudo apt-get update
          sudo apt install build-essential git
          sudo apt install cmake
          sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
          sudo apt install wayland-protocols libwayland-dev libxkbcommon-dev 
      
      - name: Build repository (macOS)
        if: runner.os == 'macOS'
        run: | 
          mkdir build && cd build 
          cmake -DCMAKE_C_FLAGS="-fsanitize=address -fno-omit-frame-pointer -g" -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer -g" -DCMAKE_LINKER_FLAGS="-fsanitize=address" -B . ..
          make 

      - name: Build repository (Linux)
        if: runner.os == 'Linux'
        run: | 
          mkdir build && cd build 
          cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_C_FLAGS="-fsanitize=address -fno-omit-frame-pointer -g" -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer -g" -DCMAKE_LINKER_FLAGS="-fsanitize=address" -B . ..
          make 
          
      - name: Install Address Sanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools

      - name: Install Address Sanitizer dependencies (macOS) 
        if: runner.os == 'macOS' 
        run: |
          brew update
          brew install llvm ninja coreutils
      
      - name: Run Google Address Sanitizer (Linux)
        if: runner.os == 'Linux'
        run: |
          #!/bin/bash
          set +e 
          
          build_dir="./build"
          executables=$(find "$build_dir" -type f | while read -r file; do
              if file "$file" | grep -q "executable"; then
                  echo "$file"
              fi
          done)
          
          TIMEOUT_DURATION=60
          DELAY_DURATION=5
          
          for exe in $executables; do
              timeout $TIMEOUT_DURATION "$exe" &
              pid=$!

              sleep $DELAY_DURATION
              kill -0 $pid &>/dev/null && kill $pid
          
              echo "--------------------------------------------------"
          done

      - name: Run Google Address Sanitizer (macOS)
        if: runner.os == 'macOS'
        run: |
          #!/bin/bash
          set +e 
          
          build_dir="./build"
          executables=$(find "$build_dir" -type f | while read -r file; do
              if file "$file" | grep -q "executable"; then
                  echo "$file"
              fi
          done)
          
          TIMEOUT_DURATION=60
          DELAY_DURATION=5
          
          for exe in $executables; do
              gtimeout $TIMEOUT_DURATION "$exe" &
              pid=$!

              sleep $DELAY_DURATION
              kill -0 $pid &>/dev/null && kill $pid
          
              echo "--------------------------------------------------"
          done
